download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/middleware_automation-wildfly-1.5.6.tar.gz
format_version: 1.0.0
name: wildfly
namespace: middleware_automation
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.5.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/middleware_automation/wildfly/versions/1.5.6/
